plugin: gcp_compute
projects:
  - devops-internship-466417
auth_kind: serviceaccount
service_account_file: ${GCP_SERVICE_ACCOUNT_FILE}

compose:
  ansible_host: networkInterfaces[0].networkIP
  ansible_user: "\"${ANSIBLE_USER}\""
  ansible_ssh_private_key_file: "\"${SSH_KEY_FILE}\""

groups:
  jumpbox: "'jumpbox' in labels.role"
  mig: "'mig' in labels.role"


